// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGDO5pedHG0AGUPbfTTLCxB-5xAPh20gs',
    appId: '1:1000125512233:android:a8e3c826576a550bb63a38',
    messagingSenderId: '1000125512233',
    projectId: 'mindospowerbi',
    storageBucket: 'mindospowerbi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5efeCnHP1qP2YTs6fWTR78HVTRxB6jQ',
    appId: '1:1000125512233:ios:5781a41e72686463b63a38',
    messagingSenderId: '1000125512233',
    projectId: 'mindospowerbi',
    storageBucket: 'mindospowerbi.appspot.com',
    iosBundleId: 'shahlathasni3.example.mindos2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5efeCnHP1qP2YTs6fWTR78HVTRxB6jQ',
    appId: '1:1000125512233:ios:5781a41e72686463b63a38',
    messagingSenderId: '1000125512233',
    projectId: 'mindospowerbi',
    storageBucket: 'mindospowerbi.appspot.com',
    iosBundleId: 'shahlathasni3.example.mindos2',
  );
}